export const CUSTOM_FONTS = [
  {
    family: 'SUIT-Light',
    url: 'url(/font/SUIT.woff2)',
    weight: '300',
    style: 'normal',
  },
  {
    family: 'SUIT-Regular',
    url: 'url(/font/SUIT.woff2)',
    weight: '400',
    style: 'normal',
  },
  {
    family: 'SUIT-Medium',
    url: 'url(/font/SUIT.woff2)',
    weight: '500',
    style: 'normal',
  },
  {
    family: 'SUIT-SemiBold',
    url: 'url(/font/SUIT.woff2)',
    weight: '600',
    style: 'normal',
  },
  {
    family: 'SUIT-Bold',
    url: 'url(/font/SUIT.woff2)',
    weight: '700',
    style: 'normal',
  },
  {
    family: 'Cormorant Garamond-Regular',
    url: 'url(/font/CormorantGaramond-Variable.ttf)',
    weight: '400',
    style: 'normal',
  },
  {
    family: 'Cormorant Garamond-Medium',
    url: 'url(/font/CormorantGaramond-Variable.ttf)',
    weight: '500',
    style: 'normal',
  },
  {
    family: 'Cormorant Garamond-SemiBold',
    url: 'url(/font/CormorantGaramond-Variable.ttf)',
    weight: '600',
    style: 'normal',
  },
  {
    family: 'Cormorant Garamond-Bold',
    url: 'url(/font/CormorantGaramond-Variable.ttf)',
    weight: '700',
    style: 'normal',
  },
  {
    family: 'Hahmlet-Regular',
    url: 'url(/font/Hahmlet-Variable.woff2)',
    weight: '400',
    style: 'normal',
  },
  {
    family: 'Hahmlet-Medium',
    url: 'url(/font/Hahmlet-Variable.woff2)',
    weight: '500',
    style: 'normal',
  },
  {
    family: 'Hahmlet-SemiBold',
    url: 'url(/font/Hahmlet-Variable.woff2)',
    weight: '600',
    style: 'normal',
  },
  {
    family: 'Hahmlet-Bold',
    url: 'url(/font/Hahmlet-Variable.woff2)',
    weight: '700',
    style: 'normal',
  },
  {
    family: 'Oswald-Regular',
    url: 'url(/font/Oswald-Variable.ttf)',
    weight: '400',
    style: 'normal',
  },
  {
    family: 'Oswald-Light',
    url: 'url(/font/Oswald-Variable.ttf)',
    weight: '300',
    style: 'normal',
  },
  {
    family: 'Oswald-Medium',
    url: 'url(/font/Oswald-Variable.ttf)',
    weight: '500',
    style: 'normal',
  },
  {
    family: 'Oswald-SemiBold',
    url: 'url(/font/Oswald-Variable.ttf)',
    weight: '600',
    style: 'normal',
  },
  {
    family: 'Oswald-Bold',
    url: 'url(/font/Oswald-Variable.ttf)',
    weight: '700',
    style: 'normal',
  },
  {
    family: 'Allura',
    url: 'url(/font/Allura-Regular.ttf)',
    weight: 'normal',
    style: 'normal',
  },
  {
    family: 'Italianno',
    url: 'url(/font/Italianno-Regular.ttf)',
    weight: 'normal',
    style: 'normal',
  },
  {
    family: 'Jost-Light',
    url: 'url(/font/Jost-Variable.ttf)',
    weight: '300',
    style: 'normal',
  },
  {
    family: 'Jost-Regular',
    url: 'url(/font/Jost-Variable.ttf)',
    weight: '400',
    style: 'normal',
  },
  {
    family: 'Jost-Medium',
    url: 'url(/font/Jost-Variable.ttf)',
    weight: '500',
    style: 'normal',
  },
  {
    family: 'Jost-SemiBold',
    url: 'url(/font/Jost-Variable.ttf)',
    weight: '600',
    style: 'normal',
  },
  {
    family: 'Jost-Bold',
    url: 'url(/font/Jost-Variable.ttf)',
    weight: '700',
    style: 'normal',
  },
  {
    family: 'Pathway Gothic One',
    url: 'url(/font/PathwayGothicOne-Regular.ttf)',
    weight: 'normal',
    style: 'normal',
  },
  {
    family: 'Barlow Condensed-Thin',
    url: 'url(/font/BarlowCondensed/BarlowCondensed-Thin.ttf)',
    weight: 'normal',
    style: 'normal',
  },
  {
    family: 'Barlow Condensed-ExtraLight',
    url: 'url(/font/BarlowCondensed/BarlowCondensed-ExtraLight.ttf)',
    weight: 'normal',
    style: 'normal',
  },
  {
    family: 'Barlow Condensed-Light',
    url: 'url(/font/BarlowCondensed/BarlowCondensed-Light.ttf)',
    weight: 'normal',
    style: 'normal',
  },
  {
    family: 'Barlow Condensed-Regular',
    url: 'url(/font/BarlowCondensed/BarlowCondensed-Regular.ttf)',
    weight: 'normal',
    style: 'normal',
  },
  {
    family: 'Barlow Condensed-Medium',
    url: 'url(/font/BarlowCondensed/BarlowCondensed-Medium.ttf)',
    weight: 'normal',
    style: 'normal',
  },
  {
    family: 'Barlow Condensed-SemiBold',
    url: 'url(/font/BarlowCondensed/BarlowCondensed-SemiBold.ttf)',
    weight: 'normal',
    style: 'normal',
  },
  {
    family: 'Barlow Condensed-Bold',
    url: 'url(/font/BarlowCondensed/BarlowCondensed-Bold.ttf)',
    weight: 'normal',
    style: 'normal',
  },
  {
    family: 'Barlow Condensed-ExtraBold',
    url: 'url(/font/BarlowCondensed/BarlowCondensed-ExtraBold.ttf)',
    weight: 'normal',
    style: 'normal',
  },
  {
    family: 'Barlow Condensed-Black',
    url: 'url(/font/BarlowCondensed/BarlowCondensed-Black.ttf)',
    weight: 'normal',
    style: 'normal',
  },
  {
    family: 'NanumSquare Neo-Light',
    url: 'url(/font/NanumSquareNeo-Variable.ttf)',
    weight: '300',
    style: 'normal',
  },
  {
    family: 'NanumSquare Neo-Regular',
    url: 'url(/font/NanumSquareNeo-Variable.ttf)',
    weight: '400',
    style: 'normal',
  },
  {
    family: 'NanumSquare Neo-Bold',
    url: 'url(/font/NanumSquareNeo-Variable.ttf)',
    weight: '700',
    style: 'normal',
  },
  {
    family: 'NanumSquare Neo-ExtraBold',
    url: 'url(/font/NanumSquareNeo-Variable.ttf)',
    weight: '800',
    style: 'normal',
  },
  {
    family: 'NanumSquare Neo-Heavy',
    url: 'url(/font/NanumSquareNeo-Variable.ttf)',
    weight: '900',
    style: 'normal',
  },
  {
    family: 'Noto Sans KR-Thin',
    url: 'url(/font/NotoSansKR-Variable.ttf)',
    weight: '100',
    style: 'normal',
  },
  {
    family: 'Noto Sans KR-ExtraLight',
    url: 'url(/font/NotoSansKR-Variable.ttf)',
    weight: '200',
    style: 'normal',
  },
  {
    family: 'Noto Sans KR-Light',
    url: 'url(/font/NotoSansKR-Variable.ttf)',
    weight: '300',
    style: 'normal',
  },
  {
    family: 'Noto Sans KR-Regular',
    url: 'url(/font/NotoSansKR-Variable.ttf)',
    weight: '400',
    style: 'normal',
  },
  {
    family: 'Noto Sans KR-Medium',
    url: 'url(/font/NotoSansKR-Variable.ttf)',
    weight: '500',
    style: 'normal',
  },
  {
    family: 'Noto Sans KR-SemiBold',
    url: 'url(/font/NotoSansKR-Variable.ttf)',
    weight: '600',
    style: 'normal',
  },
  {
    family: 'Noto Sans KR-Bold',
    url: 'url(/font/NotoSansKR-Variable.ttf)',
    weight: '700',
    style: 'normal',
  },
  {
    family: 'Noto Sans KR-ExtraBold',
    url: 'url(/font/NotoSansKR-Variable.ttf)',
    weight: '800',
    style: 'normal',
  },
  {
    family: 'Noto Sans KR-Black',
    url: 'url(/font/NotoSansKR-Variable.ttf)',
    weight: '900',
    style: 'normal',
  },
  {
    family: 'Qwigley',
    url: 'url(/font/Qwigley-Regular.ttf)',
    weight: 'normal',
    style: 'normal',
  },
  {
    family: 'DM Serif Display',
    url: 'url(/font/DMSerifDisplay-Regular.ttf)',
    weight: 'normal',
    style: 'normal',
  },
  {
    family: 'LINESeedKR-Thin',
    url: 'url(/font/LINESeedKR/LINESeedKR-Th.woff2)',
    weight: 'normal',
    style: 'normal',
  },
  {
    family: 'LINESeedKR-Regular',
    url: 'url(/font/LINESeedKR/LINESeedKR-Rg.woff2)',
    weight: 'normal',
    style: 'normal',
  },
  {
    family: 'LINESeedKR-Bold',
    url: 'url(/font/LINESeedKR/LINESeedKR-Bd.woff2)',
    weight: 'normal',
    style: 'normal',
  },
  {
    family: 'Manrope-ExtraLight',
    url: 'url(/font/Manrope-Variable.ttf)',
    weight: '200',
    style: 'normal',
  },
  {
    family: 'Manrope-Light',
    url: 'url(/font/Manrope-Variable.ttf)',
    weight: '300',
    style: 'normal',
  },
  {
    family: 'Manrope-Regular',
    url: 'url(/font/Manrope-Variable.ttf)',
    weight: '400',
    style: 'normal',
  },
  {
    family: 'Manrope-Medium',
    url: 'url(/font/Manrope-Variable.ttf)',
    weight: '500',
    style: 'normal',
  },
  {
    family: 'Manrope-SemiBold',
    url: 'url(/font/Manrope-Variable.ttf)',
    weight: '600',
    style: 'normal',
  },
  {
    family: 'Manrope-Bold',
    url: 'url(/font/Manrope-Variable.ttf)',
    weight: '700',
    style: 'normal',
  },
  {
    family: 'Manrope-ExtraBold',
    url: 'url(/font/Manrope-Variable.ttf)',
    weight: '800',
    style: 'normal',
  },
  {
    family: 'Sora-Thin',
    url: 'url(/font/Sora-Thin.ttf)',
    weight: '100',
    style: 'normal',
  },
  {
    family: 'Sora-ExtraLight',
    url: 'url(/font/Sora/Sora-ExtraLight.ttf)',
    weight: '200',
    style: 'normal',
  },
  {
    family: 'Sora-Light',
    url: 'url(/font/Sora-Variable.ttf)',
    weight: '300',
    style: 'normal',
  },
  {
    family: 'Sora-Regular',
    url: 'url(/font/Sora-Variable.ttf)',
    weight: '400',
    style: 'normal',
  },
  {
    family: 'Sora-Medium',
    url: 'url(/font/Sora-Variable.ttf)',
    weight: '500',
    style: 'normal',
  },
  {
    family: 'Sora-SemiBold',
    url: 'url(/font/Sora-Variable.ttf)',
    weight: '600',
    style: 'normal',
  },
  {
    family: 'Sora-Bold',
    url: 'url(/font/Sora-Variable.ttf)',
    weight: '700',
    style: 'normal',
  },
  {
    family: 'Sora-ExtraBold',
    url: 'url(/font/Sora-Variable.ttf)',
    weight: '800',
    style: 'normal',
  },
  {
    family: 'Mrs Saint Delafine',
    url: 'url(/font/MrsSaintDelafine-Regular.ttf)',
    weight: 'normal',
    style: 'normal',
  },
  {
    family: 'Old Standard TT-Regular',
    url: 'url(/font/OldStandardTT/OldStandardTT-Regular.ttf)',
    weight: 'normal',
    style: 'normal',
  },
  {
    family: 'Old Standard TT-Bold',
    url: 'url(/font/OldStandardTT/OldStandardTT-Bold.ttf)',
    weight: 'normal',
    style: 'normal',
  },
  {
    family: 'Old Standard TT-Italic',
    url: 'url(/font/OldStandardTT/OldStandardTT-Italic.ttf)',
    weight: 'normal',
    style: 'normal',
  },
  {
    family: 'Cormorant SC-Light',
    url: 'url(/font/CormorantSC/CormorantSC-Light.ttf)',
    weight: 'normal',
    style: 'normal',
  },
  {
    family: 'Cormorant SC-Regular',
    url: 'url(/font/CormorantSC/CormorantSC-Regular.ttf)',
    weight: 'normal',
    style: 'normal',
  },
  {
    family: 'Cormorant SC-Medium',
    url: 'url(/font/CormorantSC/CormorantSC-Medium.ttf)',
    weight: 'normal',
    style: 'normal',
  },
  {
    family: 'Cormorant SC-SemiBold',
    url: 'url(/font/CormorantSC/CormorantSC-SemiBold.ttf)',
    weight: 'normal',
    style: 'normal',
  },
  {
    family: 'Cormorant SC-Bold',
    url: 'url(/font/CormorantSC/CormorantSC-Bold.ttf)',
    weight: 'normal',
    style: 'normal',
  },
  {
    family: 'Kalam-Regular',
    url: 'url(/font/Kalam/Kalam-Regular.ttf)',
    weight: 'normal',
    style: 'normal',
  },
  {
    family: 'Kalam-Bold',
    url: 'url(/font/Kalam/Kalam-Bold.ttf)',
    weight: 'normal',
    style: 'normal',
  },
  {
    family: 'Kalam-Light',
    url: 'url(/font/Kalam/Kalam-Light.ttf)',
    weight: 'normal',
    style: 'normal',
  },
  {
    family: 'Permanent Marker',
    url: 'url(/font/PermanentMarker-Regular.ttf)',
    weight: 'normal',
    style: 'normal',
  },
  {
    family: 'Noto Serif KR-ExtraLight',
    url: 'url(/font/NotoSerifKR-Variable.ttf)',
    weight: '200',
    style: 'normal',
  },
  {
    family: 'Noto Serif KR-Light',
    url: 'url(/font/NotoSerifKR-Variable.ttf)',
    weight: '300',
    style: 'normal',
  },
  {
    family: 'Noto Serif KR-Regular',
    url: 'url(/font/NotoSerifKR-Variable.ttf)',
    weight: '400',
    style: 'normal',
  },
  {
    family: 'Noto Serif KR-Medium',
    url: 'url(/font/NotoSerifKR-Variable.ttf)',
    weight: '500',
    style: 'normal',
  },
  {
    family: 'Noto Serif KR-SemiBold',
    url: 'url(/font/NotoSerifKR-Variable.ttf)',
    weight: '600',
    style: 'normal',
  },
  {
    family: 'Noto Serif KR-Bold',
    url: 'url(/font/NotoSerifKR-Variable.ttf)',
    weight: '700',
    style: 'normal',
  },
  {
    family: 'Noto Serif KR-ExtraBold',
    url: 'url(/font/NotoSerifKR-Variable.ttf)',
    weight: '800',
    style: 'normal',
  },
  {
    family: 'Prata',
    url: 'url(/font/Prata-Regular.ttf)',
    weight: 'normal',
    style: 'normal',
  },
  {
    family: 'TenorSans',
    url: 'url(/font/TenorSans-Regular.ttf)',
    weight: 'normal',
    style: 'normal',
  },
  {
    family: 'Bodoni Moda-Light',
    url: 'url(/font/BodoniModaVariable.ttf)',
    weight: '100',
    style: 'normal',
  },
  {
    family: 'Bodoni Moda-Regular',
    url: 'url(/font/BodoniModaVariable.ttf)',
    weight: '400',
    style: 'normal',
  },
  {
    family: 'Bodoni Moda-Medium',
    url: 'url(/font/BodoniModaVariable.ttf)',
    weight: '500',
    style: 'normal',
  },
  {
    family: 'Bodoni Moda-SemiBold',
    url: 'url(/font/BodoniModaVariable.ttf)',
    weight: '600',
    style: 'normal',
  },
  {
    family: 'Bodoni Moda-Bold',
    url: 'url(/font/BodoniModaVariable.ttf)',
    weight: '700',
    style: 'normal',
  },
  {
    family: 'Noto Serif-Light',
    url: 'url(/font/NotoSerif/NotoSerif-Variable.ttf)',
    weight: '300',
    style: 'normal',
  },
  {
    family: 'Noto Serif-Regular',
    url: 'url(/font/NotoSerif/NotoSerif-Variable.ttf)',
    weight: '400',
    style: 'normal',
  },
  {
    family: 'Noto Serif-Medium',
    url: 'url(/font/NotoSerif/NotoSerif-Variable.ttf)',
    weight: '500',
    style: 'normal',
  },
  {
    family: 'Noto Serif-SemiBold',
    url: 'url(/font/NotoSerif/NotoSerif-Variable.ttf)',
    weight: '600',
    style: 'normal',
  },
  {
    family: 'Noto Serif-Bold',
    url: 'url(/font/NotoSerif/NotoSerif-Variable.ttf)',
    weight: '700',
    style: 'normal',
  },
  {
    family: 'Bona Nova-Bold',
    url: 'url(/font/BonaNova/BonaNova-Bold.ttf)',
    weight: 'normal',
    style: 'normal',
  },
  {
    family: 'Bona Nova-Italic',
    url: 'url(/font/BonaNova/BonaNova-Italic.ttf)',
    weight: 'normal',
    style: 'normal',
  },
  {
    family: 'Bona Nova-Regular',
    url: 'url(/font/BonaNova/BonaNova-Regular.ttf)',
    weight: 'normal',
    style: 'normal',
  },
  {
    family: 'IBM Plex Sans-Light',
    url: 'url(/font/IBMPlexSans-Variable.ttf)',
    weight: '200',
    style: 'normal',
  },
  {
    family: 'IBM Plex Sans-Regular',
    url: 'url(/font/IBMPlexSans-Variable.ttf)',
    weight: '400',
    style: 'normal',
  },
  {
    family: 'IBM Plex Sans-Medium',
    url: 'url(/font/IBMPlexSans-Variable.ttf)',
    weight: '500',
    style: 'normal',
  },
  {
    family: 'IBM Plex Sans-SemiBold',
    url: 'url(/font/IBMPlexSans-Variable.ttf)',
    weight: '600',
    style: 'normal',
  },
  {
    family: 'IBM Plex Sans-Bold',
    url: 'url(/font/IBMPlexSans-Variable.ttf)',
    weight: '700',
    style: 'normal',
  },
  {
    family: 'Bebas Neue',
    url: 'url(/font/BebasNeue-Regular.ttf)',
    weight: 'normal',
    style: 'normal',
  },
  {
    family: 'Anton',
    url: 'url(/font/Anton-Regular.ttf)',
    weight: 'normal',
    style: 'normal',
  },
  {
    family: 'Paperlogy-Light',
    url: 'url(/font/Paperlogy/Paperlogy-Light.ttf)',
    weight: 'normal',
    style: 'normal',
  },
  {
    family: 'Paperlogy-Regular',
    url: 'url(/font/Paperlogy/Paperlogy-Regular.ttf)',
    weight: 'normal',
    style: 'normal',
  },
  {
    family: 'Paperlogy-Medium',
    url: 'url(/font/Paperlogy/Paperlogy-Medium.ttf)',
    weight: 'normal',
    style: 'normal',
  },
  {
    family: 'Paperlogy-SemiBold',
    url: 'url(/font/Paperlogy/Paperlogy-SemiBold.ttf)',
    weight: 'normal',
    style: 'normal',
  },
  {
    family: 'Paperlogy-Bold',
    url: 'url(/font/Paperlogy/Paperlogy-Bold.ttf)',
    weight: 'normal',
    style: 'normal',
  },
  {
    family: 'Urbanist-Light',
    url: 'url(/font/Urbanist-Variable.ttf)',
    weight: '200',
    style: 'normal',
  },
  {
    family: 'Urbanist-Regular',
    url: 'url(/font/Urbanist-Variable.ttf)',
    weight: '400',
    style: 'normal',
  },
  {
    family: 'Urbanist-Medium',
    url: 'url(/font/Urbanist-Variable.ttf)',
    weight: '500',
    style: 'normal',
  },
  {
    family: 'Urbanist-SemiBold',
    url: 'url(/font/Urbanist-Variable.ttf)',
    weight: '600',
    style: 'normal',
  },
  {
    family: 'Urbanist-Bold',
    url: 'url(/font/Urbanist-Variable.ttf)',
    weight: '700',
    style: 'normal',
  },
  {
    family: 'Archivo-Light',
    url: 'url(/font/Archivo-Varibale.ttf)',
    weight: '200',
    style: 'normal',
  },
  {
    family: 'Archivo-Regular',
    url: 'url(/font/Archivo-Varibale.ttf)',
    weight: '400',
    style: 'normal',
  },
  {
    family: 'Archivo-Medium',
    url: 'url(/font/Archivo-Varibale.ttf)',
    weight: '500',
    style: 'normal',
  },
  {
    family: 'Archivo-SemiBold',
    url: 'url(/font/Archivo-Varibale.ttf)',
    weight: '600',
    style: 'normal',
  },
  {
    family: 'Archivo-Bold',
    url: 'url(/font/Archivo-Varibale.ttf)',
    weight: '700',
    style: 'normal',
  },
  {
    family: 'Archivo-ExtraBold',
    url: 'url(/font/Archivo-Varibale.ttf)',
    weight: '800',
    style: 'normal',
  },
  {
    family: 'Archivo-Black',
    url: 'url(/font/Archivo-Varibale.ttf)',
    weight: '900',
    style: 'normal',
  },
  {
    family: 'G마켓 산스-Bold',
    url: 'url(/font/GmarketSans/GmarketSansTTFBold.ttf)',
    weight: 'normal',
    style: 'normal',
  },
  {
    family: 'G마켓 산스-Light',
    url: 'url(/font/GmarketSans/GmarketSansTTFLight.ttf)',
    weight: 'normal',
    style: 'normal',
  },
  {
    family: 'G마켓 산스-Medium',
    url: 'url(/font/GmarketSans/GmarketSansTTFMedium.ttf)',
    weight: 'normal',
    style: 'normal',
  },
  {
    family: 'DM Sans-Light',
    url: 'url(/font/DMSans-Variable.ttf)',
    weight: '200',
    style: 'normal',
  },
  {
    family: 'DM Sans-Regular',
    url: 'url(/font/DMSans-Variable.ttf)',
    weight: '400',
    style: 'normal',
  },
  {
    family: 'DM Sans-Medium',
    url: 'url(/font/DMSans-Variable.ttf)',
    weight: '500',
    style: 'normal',
  },
  {
    family: 'DM Sans-SemiBold',
    url: 'url(/font/DMSans-Variable.ttf)',
    weight: '600',
    style: 'normal',
  },
  {
    family: 'DM Sans-Bold',
    url: 'url(/font/DMSans-Variable.ttf)',
    weight: '700',
    style: 'normal',
  },
  {
    family: 'Source Sans 3-Light',
    url: 'url(/font/SourceSans3-Variable.ttf)',
    weight: '200',
    style: 'normal',
  },
  {
    family: 'Source Sans 3-Regular',
    url: 'url(/font/SourceSans3-Variable.ttf)',
    weight: '400',
    style: 'normal',
  },
  {
    family: 'Source Sans 3-Medium',
    url: 'url(/font/SourceSans3-Variable.ttf)',
    weight: '500',
    style: 'normal',
  },
  {
    family: 'Source Sans 3-SemiBold',
    url: 'url(/font/SourceSans3-Variable.ttf)',
    weight: '600',
    style: 'normal',
  },
  {
    family: 'Source Sans 3-Bold',
    url: 'url(/font/SourceSans3-Variable.ttf)',
    weight: '700',
    style: 'normal',
  },
  {
    family: 'Clash Grotest-Regular',
    url: 'url(/font/ClashGrotesk-Variable.woff2)',
    weight: 'normal',
    style: 'normal',
  },
  {
    family: 'Clash Grotest-Medium',
    url: 'url(/font/ClashGrotesk-Variable.woff2)',
    weight: '500',
    style: 'normal',
  },
  {
    family: 'Clash Grotest-SemiBold',
    url: 'url(/font/ClashGrotesk-Variable.woff2)',
    weight: '600',
    style: 'normal',
  },
  {
    family: 'Clash Grotest-Bold',
    url: 'url(/font/ClashGrotesk-Variable.woff2)',
    weight: '700',
    style: 'normal',
  },
  {
    family: 'Clash Grotest-ExtraBold',
    url: 'url(/font/ClashGrotesk-Variable.woff2)',
    weight: '800',
    style: 'normal',
  },
];
