#!/usr/bin/env sh
. "$(dirname "$0")/_/husky.sh"

echo "Running ESLint before push..."
npm run lint
if [ $? -ne 0 ]; then
  echo "❌ Lint failed! Push aborted."
  exit 1
fi
echo "✅ Lint passed. Proceeding with push."
